Feature/test
OpenSourcePolitics/decidim-ludens pull request #2
Opened 2022-03-11 10:51 UTC by eliegaboriau

Version fonctionnelle de decidim ludens

2022-03-14 16:19 UTC, armandfardeau commented
Hello @eliegaboriau Could you add a github action workflow for linter and tests?

2022-03-25 16:16 UTC, paulinebessoles approved these changes

2022-03-29 14:11 UTC, armandfardeau requested changes

2022-03-29 14:11 UTC, armandfardeau commented on app/models/decidim/participative_assistant/participative_action.rb
> +      # scope :recommendations, -> { where(completed: [false, nil]).order(:points).shuffle[0,3]}
```suggestion
```

2022-04-15 13:57 UTC, paulinebessoles approved these changes

2022-04-15 15:27 UTC, merged