Last fixes
OpenSourcePolitics/decidim-ludens pull request #36
Opened 2022-09-06 14:00 UTC by eliegaboriau

add missing translations
add check when module not initialized

2022-09-06 14:12 UTC, Quentinchampenois requested changes
Just a suggestion otherwise it seems good to me !

2022-09-06 14:12 UTC, Quentinchampenois commented on app/controllers/decidim/admin/application_controller.rb
>          return unless current_organization.assistant["flash"] != ""
```suggestion
        return if current_organization.assistant["flash"].empty?
```

2022-09-08 15:32 UTC, paulinebessoles commented
Thank you @eliegaboriau! I'm just redirected on this error when trying to access the admin panel:

<img width="1013" alt="Capture d’écran 2022-09-08 à 17 31 11" src="https://user-images.githubusercontent.com/52420208/189163752-66407339-6fe8-4789-965b-c5b547ee856b.png">

Could you please fix it?

2022-10-25 12:32 UTC, paulinebessoles commented on config/locales/fr.yml
> +        cannot_activate: Le module ludens c'a pas été initialisé, vous ne pouvez donc pas l'utiliser pour l'instant. Plus d'informations <a href='https://github.com/OpenSourcePolitics/decidim-ludens/
```suggestion
        cannot_activate: L'assistant à la participation n'a pas été initialisé, vous ne pouvez donc pas l'utiliser pour l'instant. Pour l'initialiser, nous vous recommandons de consulter <a href='https://github.com/OpenSourcePolitics/decidim-ludens/blob/master/README.md'>cette notice</a>.
```

2022-10-25 12:33 UTC, paulinebessoles approved these changes
Works perfectly, thank you @eliegaboriau !

2022-10-25 12:39 UTC, Quentinchampenois approved these changes

2022-10-25 12:43 UTC, merged