refactor "participative_assistant" to "ludens"
OpenSourcePolitics/decidim-ludens pull request #5
Opened 2022-04-25 14:05 UTC by eliegaboriau

2022-04-25 14:26 UTC, paulinebessoles approved these changes

2022-04-26 10:02 UTC, Quentinchampenois requested changes
Nice refactor, I have few requests about comments documentation

2022-04-26 10:02 UTC, Quentinchampenois commented on lib/decidim/ludens.rb
> +  # This namespace holds the logic of the `ParticipativeAssistant` component. This component
Can you update this outdated comment please ?

2022-04-26 10:02 UTC, Quentinchampenois commented on lib/decidim/ludens/admin.rb
>      # This module contains all the domain logic associated to Decidim's ParticipativeAssistant
Can you update this outdated comment please ?

2022-04-26 10:02 UTC, Quentinchampenois commented on lib/decidim/ludens/admin_engine.rb
>      # This is the engine that runs on the public interface of `ParticipativeAssistant`.
Can you update this outdated comment please ?

2022-04-26 10:02 UTC, Quentinchampenois commented on lib/decidim/ludens/component.rb
>    #   resource.model_class_name = "Decidim::ParticipativeAssistant::SomeResource"
Can you update this outdated comment please ?

2022-04-26 14:12 UTC, Quentinchampenois approved these changes

2022-04-26 14:13 UTC, merged