change call to decidim ludens path
OpenSourcePolitics/decidim-ludens pull request #59
Opened 2023-05-03 15:28 UTC by eliegaboriau

Change call to decidim ludens path using gemspec full gem path

2023-05-04 07:33 UTC, Quentinchampenois requested changes
Hello, I have a change request to prevent crash 

Also I will attempt to load this branch on a decidim-app to ensure it works as expected

2023-05-04 07:33 UTC, Quentinchampenois commented on app/models/decidim/ludens/participative_action.rb
> +                            YAML.safe_load(File.read(decidim_ludens_path.join("config/participative_actions.yaml")))
`decidim_ludens_path` can be nil here, it can causes crash when call `join()` on Nil Object

2023-05-04 09:42 UTC, armandfardeau approved these changes

2023-05-05 08:55 UTC, Quentinchampenois approved these changes

2023-05-10 12:42 UTC, paulinebessoles approved these changes

2023-05-10 12:42 UTC, merged